stream_over_http_enabled: true
server:
  http_listen_port: 3200
distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317" # This is the "door" your Python app is knocking on
storage:
  trace:
    backend: local
    local:
      path: ./tmp/tempo/traces
    wal:
      path: ./tmp/tempo/wal